### step 49: register request hamishe beine header va body ye khat fasele bzar
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "userName" :"ehsan1" ,
  "email" :"ehsan1@google.com" ,
  "mobile" :"09132862170" ,
  "password" : "12345678904",
  "confirm_password" :"12345678904" 
}

### step 53: login request hamishe beine header va body ye khat fasele bzar
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer ${{$dotenv token}}

{
  "userName" : "ehsan1" ,
  "password" : "12345678904"
}