### step 64: get user profile
GET http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}

### step 6x : update user profile
POST http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "firstName":"ehsan", 
    "lastName":"hasanpour", 
    "skills":["react" , "next.js" , "node.js" , "typescript"]
}